---

homebrew:
  taps:
    - homebrew/command-not-found
    - falcosuessgott/tap
    - starkandwayne/cf

  formulae:
    - git
    - python
    - nmap
    - openssl
    - wget
    - curl
    - jq
    - htop
    - gopass
    - mise
    - direnv
    - yq
    - autojump
    - s5cmd
    - tldr
    - ca-certificates
    - when
    - docker
    - ripgrep
    - mysql-client
    - session-manager-plugin
    - shellcheck
    - ipcalc
    - lsd
    - vsh
    - vkv
    - safe
    - pug


  casks:
    - google-chrome
    - firefox
    - slack
    - spotify
    - arc
    - cursor
    - libreoffice
    - postman


appstore_apps:
  - { id: 441258766, name: "Magnet" }
  - { id: 937984704, name: "Amphetamine" }
  - { id: 985367838, name: "Microsoft Outlook" }
  - { id: 1446549608, name: "Mozilla Firefox" }

cursor_extensions:
  - { name: "Gitignore", id: "codezombiech.gitignore" }
  - { name: "Git History", id: "donjayamanne.githistory" }
  - { name: "Git Lens", id: "eamodio.gitlens" }
  - { name: "Terraform", id: "hashicorp.terraform" }
  - { name: "Pretty formatter", id: "mblode.pretty-formatter" }
  - { name: "Compare folders", id: "moshfeu.compare-folders" }
  - { name: "Diff Merge", id: "moshfeu.diff-merge" }
  - { name: "Gitignore", id: "codezombiech.gitignore" }
  - { name: "Python", id: "ms-python.python" }
  - { name: "Makefile", id: "ms-vscode.makefile-tools" }
  - { name: "Trailing space", id: "shardulm94.trailing-spaces" }
  - { name: "Shellcheck", id: "timonwong.shellcheck" }
  - { name: "Markdown", id: "yzhang.markdown-all-in-one" }
  - { name: "Gitlab", id: "gitlab.gitlab-workflow" }
  - { name: "AWS Toolkit", id: "amazonwebservices.aws-toolkit-vscode" }
  - { name: "Ansible", id: "redhat.ansible" }

mise_tools:
  awscli: "latest"
  kubectl: "latest"
  k9s: "latest"
  kubectx: "latest"
  helm: "latest"
  packer: "latest"
  infracost: "latest"
  terraform: "latest"
  tflint: "latest"
  tfupdate: "latest"
  terraformer: "latest"
  terraform-docs: "latest"
  pre-commit: "latest"
  ghorg: "latest"
  trivy: "latest"
  glab: "latest"
  vault: "latest"
  updatecli: "latest"
  pipx: "latest"
  granted: "latest"

username: "{{ ansible_user_id }}"


cursor_settings:
  "extensions.verifySignature": false
  "editor.bracketPairColorization.enabled": true
  "editor.mouseWheelZoom": true
  "terminal.external.osxExec": "Rosetta iTerm.app"
  "files.autoSave": "afterDelay"
  "gitlab.instanceUrl": "https://gitlab.com"
  "editor.minimap.enabled": false
  "git.confirmSync": false
  "gitlens.remotes":
    - domain: "gitlab.com"
      type: "GitLab"
  "workbench.enableExperiments": false
  "redhat.telemetry.enabled": false
  "files.associations":
    "*.yml": "ansible"
    "*.tf": "terraform"
    "*.tfvars": "terraform"
    ".gitlab-ci.yml": "plaintext"
  "[json]":
    "editor.defaultFormatter": "vscode.json-language-features"
  "git.enableSmartCommit": true
  "[terraform]":
    "editor.defaultFormatter": "hashicorp.terraform"
    "editor.formatOnSave": true
    "editor.formatOnSaveMode": "file"
  "[terraform-vars]":
    "editor.defaultFormatter": "hashicorp.terraform"
    "editor.formatOnSave": true
    "editor.formatOnSaveMode": "file"
  "editor.formatOnSave": false
  "search.exclude":
    "**/.git": true
    "**/.terraform": true
  "git.followTagsWhenSync": true
  "git.mergeEditor": false
  "[ansible]":
    "editor.detectIndentation": true
    "editor.insertSpaces": true
    "editor.tabSize": 2
    "editor.quickSuggestions":
      "comments": true
      "other": true
      "strings": true
  "ansible.executionEnvironment.volumeMounts": []
  "editor.codeActionsOnSave": {}
  "trailing-spaces.highlightCurrentLine": false
  "window.zoomLevel": 1
  "terraform.languageServer.enable": true
  "terraform.experimentalFeatures.prefillRequiredFields": true
  "terraform.codelens.referenceCount": false
  "editor.largeFileOptimizations": true
  "editor.suggest.preview": false
  "extensions.autoUpdate": "onlyEnabledExtensions"
  "aws.codeWhisperer.shareCodeWhispererContentWithAWS": false
  "aws.telemetry": false
  "ansible.validation.lint.enabled": false
  "gitlab.duoChat.enabled": false
  "gitlens.ai.experimental.provider": "openai"
  "gitlens.ai.experimental.openai.model": "gpt-4-1106-preview"
  "gitlab.duoCodeSuggestions.enabled": false
  "diffEditor.codeLens": true
  "diffEditor.ignoreTrimWhitespace": false

cursor_keybindings:
  - key: "ctrl+shift+j"
    command: "workbench.action.toggleMaximizedPanel"

  - key: "alt+space"
    command: "editor.action.triggerSuggest"
    when: "editorHasCompletionItemProvider && textInputFocus && !editorReadonly"

  - key: "ctrl+space"
    command: "-editor.action.triggerSuggest"
    when: "editorHasCompletionItemProvider && textInputFocus && !editorReadonly"

  - key: "shift+cmd+s"
    command: "workbench.action.terminal.runSelectedText"

  - key: "shift+cmd+[Period]"
    command: "-toggleExplainMode"
    when: "suggestWidgetVisible"

  - key: "shift+cmd+m"
    command: "-workbench.actions.view.problems"
    when: "workbench.panel.markers.view.active"

  - key: "shift+cmd+m"
    command: "continue.focusContinueInputWithoutClear"

  - key: "shift+cmd+l"
    command: "-continue.focusContinueInputWithoutClear"

pipx_executable: "/Users/{{ ansible_user }}/.local/share/mise/installs/pipx/latest/bin/pipx"
