---

homebrew:
  taps:
    - homebrew/command-not-found
    - falcosuessgott/tap
    - starkandwayne/cf
    - suzuki-shunsuke/tfmv

  formulae:
    - git                     # Version control system for tracking changes in files
    - python                  # Interpreted programming language for general-purpose programming
    - nmap                    # Network exploration and security auditing utility
    - openssl                 # Cryptography and SSL/TLS toolkit
    - wget                    # Utility for non-interactive download of files from the web
    - curl                    # Command line tool for transferring data with URLs
    - jq                      # Lightweight and flexible command-line JSON processor
    - htop                    # Interactive process viewer and system monitor
    - gopass                  # Password manager with Git integration
    - mise                    # Dev tools version manager (formerly rtx)
    - direnv                  # Environment variable manager for the shell
    - yq                      # Command-line YAML, XML, TOML processor - jq wrapper for YAML
    - autojump                # Shell extension to jump to frequently used directories
    - s5cmd                   # Fast S3 and local filesystem execution tool
    - tldr                    # Simplified and community-driven man pages
    - ca-certificates         # Common CA certificates for SSL applications
    - when                    # Simple calendar and task management tool
    - ripgrep                 # Fast line-oriented search tool (alternative to grep)
    - mysql-client            # MySQL database client
    - session-manager-plugin  # AWS Session Manager plugin for the AWS CLI
    - shellcheck              # Static analysis tool for shell scripts
    - ipcalc                  # Calculator for IP addresses
    - lsd                     # Modern ls command with colorful output and icons
    - vsh                     # HashiCorp Vault interactive shell
    - vkv                     # Command-line interface for HashiCorp Vault key-value operations
    - safe                    # Command-line interface to Vault for secrets management
    - pug                     # CLI tool for managing terraform resources and state interactively
    - tfautomv                # Terraform automatic resource move suggestions
    - tfmv                    # Terraform state mv command generator
    - hcledit                 # CLI tool for editing HCL files


  casks:
    - google-chrome
    - firefox
    - slack
    - spotify
    - arc
    - cursor
    - libreoffice
    - postman
    - warp

iterm2_enabled: false

appstore_apps:
  - { id: 441258766, name: "Magnet" }
  - { id: 937984704, name: "Amphetamine" }
  - { id: 985367838, name: "Microsoft Outlook" }
  - { id: 1446549608, name: "Mozilla Firefox" }
  - { id: 1352778147, name: "Bitwarden" }

cursor_extensions:
  - { name: "Gitignore", id: "codezombiech.gitignore" }
  - { name: "Git History", id: "donjayamanne.githistory" }
  - { name: "Git Lens", id: "eamodio.gitlens" }
  - { name: "Terraform", id: "hashicorp.terraform" }
  - { name: "Pretty formatter", id: "mblode.pretty-formatter" }
  - { name: "Compare folders", id: "moshfeu.compare-folders" }
  - { name: "Diff Merge", id: "moshfeu.diff-merge" }
  - { name: "Gitignore", id: "codezombiech.gitignore" }
  - { name: "Python", id: "ms-python.python" }
  - { name: "Makefile", id: "ms-vscode.makefile-tools" }
  - { name: "Trailing space", id: "shardulm94.trailing-spaces" }
  - { name: "Shellcheck", id: "timonwong.shellcheck" }
  - { name: "Markdown", id: "yzhang.markdown-all-in-one" }
  - { name: "Gitlab", id: "gitlab.gitlab-workflow" }
  - { name: "AWS Toolkit", id: "amazonwebservices.aws-toolkit-vscode" }
  - { name: "Ansible", id: "redhat.ansible" }

mise_tools:
  awscli: "latest"
  kubectl: "latest"
  k9s: "latest"
  kubectx: "latest"
  helm: "latest"
  packer: "latest"
  infracost: "latest"
  terraform: "latest"
  tflint: "latest"
  tfupdate: "latest"
  terraformer: "latest"
  terraform-docs: "latest"
  pre-commit: "latest"
  ghorg: "latest"
  trivy: "latest"
  glab: "latest"
  vault: "latest"
  updatecli: "latest"
  granted: "latest"
  uv: "latest"

username: "{{ ansible_user_id }}"


cursor_settings:
  "extensions.verifySignature": false
  "editor.bracketPairColorization.enabled": true
  "editor.mouseWheelZoom": true
  "terminal.external.osxExec": "Warp.app"
  "files.autoSave": "afterDelay"
  "gitlab.instanceUrl": "https://gitlab.com"
  "editor.minimap.enabled": false
  "git.confirmSync": false
  "gitlens.remotes":
    - domain: "gitlab.com"
      type: "GitLab"
  "redhat.telemetry.enabled": false
  "files.associations":
    "*.yml": "ansible"
    "*.tf": "terraform"
    "*.tfvars": "terraform"
    ".gitlab-ci.yml": "plaintext"
    "*.md": "markdown"
  "[json]":
    "editor.defaultFormatter": "vscode.json-language-features"
  "git.enableSmartCommit": true
  "[terraform]":
    "editor.defaultFormatter": "hashicorp.terraform"
    "editor.formatOnSave": true
    "editor.formatOnSaveMode": "file"
  "[terraform-vars]":
    "editor.defaultFormatter": "hashicorp.terraform"
    "editor.formatOnSave": true
    "editor.formatOnSaveMode": "file"
  "editor.formatOnSave": false
  "search.exclude":
    "**/.git": true
    "**/.terraform": true
  "git.followTagsWhenSync": true
  "git.mergeEditor": false
  "[ansible]":
    "editor.detectIndentation": true
    "editor.insertSpaces": true
    "editor.tabSize": 2
    "editor.quickSuggestions":
      "comments": true
      "other": true
      "strings": true
  "ansible.executionEnvironment.volumeMounts": []
  "editor.codeActionsOnSave": {}
  "trailing-spaces.highlightCurrentLine": false
  "window.zoomLevel": 1
  "terraform.languageServer.enable": true
  "terraform.experimentalFeatures.prefillRequiredFields": true
  "terraform.codelens.referenceCount": false
  "editor.largeFileOptimizations": true
  "editor.suggest.preview": false
  "extensions.autoUpdate": "onlyEnabledExtensions"
  "aws.codeWhisperer.shareCodeWhispererContentWithAWS": false
  "aws.telemetry": false
  "ansible.validation.lint.enabled": false
  "gitlab.duoChat.enabled": false
  "gitlens.ai.experimental.provider": "openai"
  "gitlens.ai.experimental.openai.model": "gpt-4-1106-preview"
  "gitlab.duoCodeSuggestions.enabled": false
  "diffEditor.codeLens": true
  "diffEditor.ignoreTrimWhitespace": false
  "workbench.enableExperiments": false
  "window.commandCenter": 1
  "workbench.colorTheme": "Cursor Dark Midnight"
  "cursor.cpp.disabledLanguages":
    - "plaintext"

cursor_keybindings:
  - key: "ctrl+shift+j"
    command: "workbench.action.toggleMaximizedPanel"

  - key: "alt+space"
    command: "editor.action.triggerSuggest"
    when: "editorHasCompletionItemProvider && textInputFocus && !editorReadonly"

  - key: "ctrl+space"
    command: "-editor.action.triggerSuggest"
    when: "editorHasCompletionItemProvider && textInputFocus && !editorReadonly"

  - key: "shift+cmd+s"
    command: "workbench.action.terminal.runSelectedText"

  - key: "shift+cmd+[Period]"
    command: "-toggleExplainMode"
    when: "suggestWidgetVisible"

  - key: "shift+cmd+m"
    command: "-workbench.actions.view.problems"
    when: "workbench.panel.markers.view.active"

  - key: "shift+alt+m"
    command: "editor.action.selectHighlights"
    when: "editorFocus"

  - key: "alt+m"
    command: "editor.action.addSelectionToNextFindMatch"
    when: "editorFocus"

git_enabled: true
git_username: theo
git_email: theo.poccard@gmail.com


# Set applications in Dock
display_applications:
  - /Applications/Arc.app
  - /Applications/Slack.app
  - /Applications/Cursor.app
  - /Applications/Firefox.app
  - /Applications/Warp.app
  - /Applications/Google\ Chrome.app
  - /Applications/Spotify.app
  - /Applications/Bitwarden.app
  - /System/Applications/Messages.app
  - /System/Applications/Calendar.app
  - /System/Applications/Notes.app
  - "\"/System/Applications/System Settings.app\""
  - /System/Applications/Launchpad.app

# In your playbook vars or group_vars/host_vars
warp_workflows:
  - workflow_name: "Multiple terraform state rm"
    workflow_command: !unsafe '"{{terraform_binary}} state list | grep {{search}} | xargs -I {} {{terraform_binary}} state rm {}"'
    workflow_tags:
      - devops
      - terraform
    workflow_description: "Multiple terraform state rm"
    workflow_arguments:
      - name: search
        description: "The variable to search for"
        default_value: "World"
      - name: terraform_binary
        description: "The terraform binary to use"
        default_value: "terraform"
  - workflow_name: "AWS ECR login"
    workflow_command: !unsafe '"aws ecr get-login-password --region {{region}} --profile {{aws_profile}} | docker login --username AWS --password-stdin {{aws_account_id}}.dkr.ecr.{{region}}.amazonaws.com"'
    workflow_tags:
      - devops
      - aws
    workflow_description: "AWS ECR login"
    workflow_arguments:
      - name: region
        description: "The AWS region to use"
        default_value: "eu-west-3"
      - name: aws_account_id
        description: "The AWS account ID"
        default_value: "0000000000"
      - name: aws_profile
        description: "The AWS profile to use"
        default_value: "default"
  - workflow_name: "Rename multiple files recursively"
    workflow_command: !unsafe 'zmv ''(**/){{filename}}'' ''${1}{{new_filename}}'''
    workflow_tags:
      - linux
    workflow_description: "Rename multiple files recursively"
    workflow_arguments:
      - name: filename
        description: "The filename to rename"
      - name: new_filename
        description: "The new filename"
  - workflow_name: "Show all mysql grants for all users"
    workflow_command: "SELECT CONCAT('SHOW GRANTS FOR ''',user,'''@''',host,''';') FROM mysql.user;"
    workflow_tags:
      - mysql
    workflow_description: "Show all mysql grants for all users"