---

homebrew:
  taps: []

  formulae:
    - git
    - python
    - nmap
    - openssl
    - wget
    - curl
    - jq
    - htop
    - gopass
    - mise
    - direnv
    - yq
    - autojump

  casks:
    - google-chrome
    - firefox
    - slack
    - spotify
    - arc
    - cursor
    - libreoffice
    - postman


appstore_apps:
  - { id: 441258766, name: "Magnet" }
  - { id: 937984704, name: "Amphetamine" }

cursor_extensions:
  - { name: "Cursor AI", id: "https://cursor.com/api/extension/1234567890" }
