---
- name: Converge
  hosts: all
  become: true
  gather_facts: true
  vars:
    ansible_user: root
    mise_tools:
      uv: latest
  tasks:
    - name: Include gita role
      ansible.builtin.include_role:
        name: gita
