---
# Debian/Ubuntu specific variables for Warp Terminal role

# Default installation method for Debian/Ubuntu

warp_package_dependencies:
  - gnupg
  - gpg
  - libasound2t64

warp_install_method: "apt"

# Workflow directory path for Linux
warp_workflows_dir: "{{ ansible_facts.env.HOME }}/.local/share/warp-terminal/workflows"
warp_parent_dir: "{{ ansible_facts.env.HOME }}/.local/share/warp-terminal"

warp_package_name: warp-terminal
warp_download_url: "https://app.warp.dev/get_warp?package=deb"
warp_apt_state: present
warp_apt_key_id: 0913165C78D5B7A41B42AC657FF7AB39D60F803F
warp_gpg_key_url: "https://releases.warp.dev/linux/keys/warp.asc"
