---
- name: Converge
  hosts: all
  become: true
  gather_facts: true
  vars:
    mise_tools:
      uv: "latest"
  tasks:
    - name: Include mise role
      ansible.builtin.include_role:
        name: mise

    - name: Include uv role
      ansible.builtin.include_role:
        name: uv
