---
# tasks file for roles/pipx

- name: Run pipx ensurepath to add pipx binary paths
  ansible.builtin.command: "{{ item }} ensurepath"
  register: ensurepath_result
  changed_when: ensurepath_result.rc != 0
  with_fileglob:
    - "/Users/{{ ansible_user }}/.local/share/mise/installs/pipx/*/bin/pipx"
