---
# tasks file for roles/pipx

- name: Run pipx ensurepath to add pipx binary paths
  ansible.builtin.command: "{{ pipx_executable }} ensurepath"
  register: ensurepath_result
  changed_when: ensurepath_result.rc != 0
