# SPDX-License-Identifier: MIT-0
---
galaxy_info:
  role_name: rancher_desktop
  namespace: ansible_mgmt_laptop
  author: Theo Poccard
  description: Rancher Desktop installation for macOS and Ubuntu
  license: MIT
  min_ansible_version: "2.14"

  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
        - noble
    - name: MacOSX
      versions:
        - all

  galaxy_tags:
    - rancher
    - docker
    - kubernetes
    - containers

dependencies: []
