---
cursor_extensions:
  - "dbaeumer.vscode-eslint"
  - "esbenp.prettier-vscode"
  - "ms-python.python"
  - "golang.go"
  - "hashicorp.terraform"
  - "redhat.ansible"
  - "ms-azuretools.vscode-docker"
  - "github.copilot"
  # Add more extensions as needed 

users:
  username: "{{ ansible_user_id }}"
  # visual_studio_code_settings: "{{ cursor_settings }}"

cursor_settings_overwrite: false
cursor_keybindings_overwrite: false

cursor_settings:
  extensions.verifySignature: false

cursor_keybindings: {}