---
galaxy_info:
  role_name: uv
  author: tpo
  description: Installs uv Python package installer
  license: MIT
  min_ansible_version: "2.10"
  platforms:
    - name: MacOSX
      versions:
        - all

  galaxy_tags:
    - uv
    - python
    - package
    - installer
    - development
    - tools

dependencies:
  - role: mise