---
- name: Ensure ghorg is installed via homebrew
  community.general.homebrew:
    name: gabrie30/utils/ghorg
    state: present

- name: Create ghorg config directory
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config/ghorg"
    state: directory
    mode: '0755'

- name: Configure ghorg default settings
  ansible.builtin.template:
    src: ghorgconfig.yml.j2
    dest: "{{ ansible_env.HOME }}/.config/ghorg/conf.yaml"
    mode: '0644' 