---
- name: Install Warp via Homebrew
  community.general.homebrew_cask:
    name: "{{ warp_homebrew_cask_name }}"
    state: "{{ warp_homebrew_cask_state }}"
    greedy: "{{ warp_homebrew_cask_greedy }}"
  register: warp_homebrew_result
  when:
    - warp_enabled | bool
