---

- name: Install dependencies
  ansible.builtin.apt:
    name: "{{ warp_package_dependencies }}"
    state: present
    update_cache: true
  become: true
  tags: warp

- name: Add an Apt signing key to a specific keyring file
  ansible.builtin.apt_key:
    id: "{{ warp_apt_key_id }}"
    url: "{{ warp_gpg_key_url }}"
    keyring: /etc/apt/keyrings/warpdotdev.gpg
  become: true
  tags: warp

- name: Add Warp apt repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/warpdotdev.gpg] https://releases.warp.dev/linux/deb stable main"
    state: present
    filename: "warpdotdev"
  become: true
  tags: warp

- name: Install Warp DEB package
  ansible.builtin.apt:
    name: "{{ warp_package_name }}"
    state: "{{ warp_apt_state }}"
  become: true
  register: warp_apt_result
  tags: warp
