---
galaxy_info:
  author: saewyn
  description: Install and configure mise (formerly rtx)
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - noble
    - name: MacOSX
      versions:
        - all

dependencies: []
