---
# Debian/Ubuntu installation tasks for zsh

- name: Install zsh and related packages via apt
  ansible.builtin.apt:
    name:
      - git  # Required for cloning Oh My Zsh and themes
      - zsh
      - zsh-autosuggestions
      - zsh-syntax-highlighting
      - autojump
      - xclip
    state: present
    update_cache: true
  become: true
  tags: zsh

- name: Set default shell to zsh
  ansible.builtin.user:
    name: "{{ ansible_facts.user_id }}"
    shell: /usr/bin/zsh
  become: true
  tags: zsh

- name: Check if oh-my-zsh is installed
  ansible.builtin.stat:
    path: "{{ ansible_facts.env.HOME }}/.oh-my-zsh"
  register: zsh_oh_my_zsh_installed
  tags: zsh

- name: Install Oh My Zsh
  ansible.builtin.git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: "{{ ansible_facts.env.HOME }}/.oh-my-zsh"
    depth: 1
  tags: zsh
  when: not zsh_oh_my_zsh_installed.stat.exists

- name: Install powerlevel10k theme
  ansible.builtin.git:
    repo: "{{ zsh_powerlevel10k.theme.url }}"
    dest: "{{ ansible_facts.env.HOME }}/.oh-my-zsh/custom/themes/powerlevel10k"
    version: "{{ zsh_powerlevel10k.theme.version }}"
  tags: zsh

- name: Copy .zshrc
  ansible.builtin.template:
    src: "templates/.zshrc.j2"
    dest: "{{ ansible_facts.env.HOME }}/.zshrc"
    mode: "0644"
  tags: zsh

- name: Copy .p10k.zsh
  ansible.builtin.copy:
    src: "p10k.zsh"
    dest: "{{ ansible_facts.env.HOME }}/.p10k.zsh"
    mode: "0644"
  tags: zsh
