---
# macOS installation tasks for zsh

- name: Install necessary zsh homebrew packages
  community.general.homebrew:
    name:
      - zsh
      - zsh-completions
      - zsh-autosuggestions
      - zsh-syntax-highlighting
    state: present
  tags: zsh

- name: Set default shell to zsh
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    shell: /bin/zsh
  tags: zsh

- name: Check if oh-my-zsh is installed
  ansible.builtin.stat:
    path: "{{ ansible_env.HOME }}/.oh-my-zsh"
  register: zsh_oh_my_zsh_installed

- name: Install Oh My Zsh
  ansible.builtin.git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh"
    depth: 1
  tags: zsh
  when: not zsh_oh_my_zsh_installed.stat.exists

- name: Install powerlevel10k theme
  ansible.builtin.git:
    repo: "{{ zsh_powerlevel10k.theme.url }}"
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/themes/powerlevel10k"
    version: "{{ zsh_powerlevel10k.theme.version }}"
  tags: zsh

- name: Copy .zshrc
  ansible.builtin.template:
    src: "templates/.zshrc.j2"
    dest: "{{ ansible_env.HOME }}/.zshrc"
    mode: "0644"
  tags: zsh

- name: Copy .p10k.zsh
  ansible.builtin.copy:
    src: "p10k.zsh"
    dest: "{{ ansible_env.HOME }}/.p10k.zsh"
    mode: "0644"
  tags: zsh
