---
- name: Install required dependencies for mise on Ubuntu/Debian
  ansible.builtin.apt:
    name:
      - curl
      - gpg
      - wget
      - git
      - zip
      - unzip
    state: present
    update_cache: true
  become: true

- name: Create /etc/apt/keyrings directory
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: "0755"
  become: true

- name: Download and add mise GPG key
  ansible.builtin.shell: |
    wget --tries=3 --waitretry=5 -qO - https://mise.jdx.dev/gpg-key.pub | gpg --dearmor | tee /etc/apt/keyrings/mise-archive-keyring.gpg > /dev/null
  args:
    creates: /etc/apt/keyrings/mise-archive-keyring.gpg
  become: true

- name: Add mise apt repository
  ansible.builtin.copy:
    content: "deb [signed-by=/etc/apt/keyrings/mise-archive-keyring.gpg arch={{ 'amd64' if ansible_facts.architecture == 'x86_64' else 'arm64' }}] https://mise.jdx.dev/deb
      stable main"
    dest: /etc/apt/sources.list.d/mise.list
    mode: "0644"
  become: true

- name: Install mise
  ansible.builtin.apt:
    name: mise
    state: present
    update_cache: true
  become: true
  when: mise_check.rc != 0
