---
- name: Include distribution-specific installation tasks
  ansible.builtin.include_tasks: "install-{{ ansible_distribution }}.yml"

- name: Configure mise
  ansible.builtin.include_tasks: configure-mise.yml

- name: Configure shell integration
  ansible.builtin.include_tasks: configure-shell.yml
