---
- name: Arc Browser - Configure defaults
  community.general.osx_defaults:
    domain: company.thebrowser.Browser
    key: "{{ item.key }}"
    type: "{{ item.type }}"
    value: "{{ item.value }}"
    state: present
  with_items: "{{ arc.defaults }}"
  tags: arc, defaults
