---
zsh_ohmyzsh:
  url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
  plugins:
    - command-not-found
    - virtualenv
    - git
    - copyfile
    - autojump
    - fastfile
    - kubectl

zsh_powerlevel10k:
  theme:
    url: https://github.com/romkatv/powerlevel10k.git
    version: master
