---
galaxy_info:
  role_name: base_tools
  namespace: ansible_mgmt_laptop
  author: Theo Poccard
  description: Base development tools installation for macOS and Ubuntu
  license: MIT
  min_ansible_version: "2.14"

  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
        - noble
    - name: MacOSX
      versions:
        - all

  galaxy_tags:
    - development
    - tools
    - packages

dependencies:
  - role: mise
  - role: uv
