---
galaxy_info:
  role_name: gita
  author: TheoPoc
  namespace: local
  description: Installs gita tool using uv
  license: MIT
  min_ansible_version: "2.10"
  platforms:
    - name: MacOSX
      versions:
        - all
    - name: Ubuntu
      versions:
        - all

  galaxy_tags:
    - gita
    - development
    - tools

dependencies:
  - role: mise
  - role: uv
