---
dependency:
  name: galaxy
  options:
    requirements-file: ${MOLECULE_SCENARIO_DIRECTORY}/requirements.yml

driver:
  name: docker

platforms:
  - name: ubuntu-base-tools
    image: geerlingguy/docker-ubuntu2404-ansible:latest
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
  - name: debian-base-tools
    image: geerlingguy/docker-debian12-ansible:latest
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true

scenario:
  test_sequence:
    - dependency
    - create
    - converge
    - idempotence
    - verify
    - destroy

provisioner:
  name: ansible
  playbooks:
    converge: converge.yml
    verify: verify.yml
  inventory:
    host_vars:
      ubuntu-base-tools:
        ansible_user: root
        debian_apt_packages:
          - git
          - python3
          - python3-pip
          - curl
          - wget
          - unzip
          - jq
          - ripgrep
          - htop
          - shellcheck
        debian_apt_repositories: {}
        debian_deb_applications: {}
        debian_binary_applications: {}
      debian-base-tools:
        ansible_user: root
        debian_apt_packages:
          - git
          - python3
          - python3-pip
          - curl
          - wget
          - unzip
          - jq
          - ripgrep
          - htop
          - shellcheck
        debian_apt_repositories: {}
        debian_deb_applications: {}
        debian_binary_applications: {}
  env:
    ANSIBLE_ALLOW_BROKEN_CONDITIONALS: "True"
    ANSIBLE_ROLES_PATH: ../../../

verifier:
  name: ansible
