---
dependency:
  name: galaxy
  options:
    requirements-file: ${MOLECULE_SCENARIO_DIRECTORY}/requirements.yml

driver:
  name: docker

platforms:
  - name: ubuntu-24-04-docker-mode
    image: geerlingguy/docker-ubuntu2404-ansible:latest
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
    groups:
      - docker_mode

  - name: ubuntu-24-04-rancher-mode
    image: geerlingguy/docker-ubuntu2404-ansible:latest
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
    groups:
      - rancher_mode

  - name: debian-12-docker-mode
    image: geerlingguy/docker-debian12-ansible:latest
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
    groups:
      - docker_mode

  - name: debian-12-rancher-mode
    image: geerlingguy/docker-debian12-ansible:latest
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
    groups:
      - rancher_mode

scenario:
  test_sequence:
    - dependency
    - create
    - converge
    - verify
    - destroy

provisioner:
  name: ansible
  playbooks:
    converge: converge.yml
    verify: verify.yml
  env:
    ANSIBLE_ALLOW_BROKEN_CONDITIONALS: "True"
    ANSIBLE_ROLES_PATH: ../../../
  inventory:
    group_vars:
      docker_mode:
        docker_mode: "docker"
      rancher_mode:
        docker_mode: "rancher-desktop"

verifier:
  name: ansible
