---
galaxy_info:
  role_name: zsh
  namespace: ansible_mgmt_laptop
  author: Theo Poccard
  description: Zsh shell installation and configuration with Oh My Zsh
  license: MIT
  min_ansible_version: "2.14"

  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
        - noble
    - name: MacOSX
      versions:
        - all

  galaxy_tags:
    - zsh
    - shell
    - terminal
