---
# MacOS-specific installation for vim

- name: Install homebrew formulae
  community.general.homebrew:
    name: "{{ vim_package }}"
    state: present
    path: "{{ vim_homebrew_path }}"
  tags: vim
