---
galaxy_info:
  role_name: copier
  author: tpo
  description: Installs copier using pipx
  license: MIT
  min_ansible_version: "2.10"
  platforms:
    - name: MacOSX
      versions:
        - all

  galaxy_tags:
    - copier
    - pipx
    - development
    - tools

dependencies:
  - role: mise 