# SPDX-License-Identifier: MIT-0
---
galaxy_info:
  role_name: docker
  namespace: ansible_mgmt_laptop
  author: Theo Poccard
  description: Docker installation (Docker Desktop/Engine or Rancher Desktop) for macOS, Ubuntu, and Debian
  license: MIT
  min_ansible_version: "2.14"

  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
        - noble
    - name: Debian
      versions:
        - bookworm
    - name: MacOSX
      versions:
        - all

  galaxy_tags:
    - docker
    - containers
    - rancher
    - kubernetes

dependencies: []
